language: php

services: mariadb
addons:
    mariadb: '10.3'

before_install:
    - phpenv config-rm xdebug.ini || return 0
    - pecl install pcov
    - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -uroot -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'
    - mysql -utravis -e 'CREATE DATABASE IF NOT EXISTS datagrid;'
    - mysql -utravis -e 'CREATE DATABASE IF NOT EXISTS datagrid1;'
    - mysql -utravis -e 'CREATE DATABASE IF NOT EXISTS datagrid2;'

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - ./vendor/bin/phpcs --standard=./ruleset.xml --colors -p src/ tests/
    - ./vendor/bin/phpstan analyse -c ./phpstan.neon -l 8 src/ tests/
    - ./vendor/bin/phpunit -c ./vendor/hanaboso/php-check-utils/phpunit.xml.dist tests/Integration
    - ./vendor/bin/paratest -c ./vendor/hanaboso/php-check-utils/phpunit.xml.dist -p 4 --coverage-clover var/coverage.xml --whitelist src tests
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - php coveralls.phar --verbose --config .coveralls.yml

php:
    - 7.4

branches:
    only:
        - master

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false