version: '3.5'

services:
    php:
        image: hanabosocom/php-dev:php-8.2-alpine
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            COMPOSER_HOME: ${HOME}/dev/.composer
            MARIA_HOST: 'mariadb'
            MARIA_USER: 'root'
            MARIA_PASSWORD: 'root'
        volumes:
            - ./:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached

    mariadb:
        image: mariadb:10
        command: "mysqld --innodb_flush_method=nosync"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb:/var/lib/mysql

volumes:
    mariadb: {}
