version: '3.3'

services:
    php:
        image: dkr.hanaboso.net/hanaboso/datagrid/app:dev
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
            - ${HOME}/.composer:/srv/.composer

    mariadb:
        image: mariadb:latest
        command: "mysqld --innodb_flush_method=nosync"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb:/var/lib/mysql

volumes:
    mariadb: {}
